
/*
 * Copyright (c) SiteWhere, LLC. All rights reserved. http://www.sitewhere.com
 *
 * The software in this package is published under the terms of the CPAL v1.0
 * license, a copy of which has been included with this distribution in the
 * LICENSE.txt file.
 */

package com.openiot.assetmodule.magento.ws;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import javax.xml.namespace.QName;
import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

/**
 * This class was generated by Apache CXF 2.3.1
 * Fri Oct 18 03:30:17 EDT 2013
 * Generated source version: 2.3.1
 * 
 */

public final class MageApiModelServerWsiHandlerPortType_MageApiModelServerWsiHandlerPort_Client {

    private static final QName SERVICE_NAME = new QName("urn:Magento", "MagentoService");

    private MageApiModelServerWsiHandlerPortType_MageApiModelServerWsiHandlerPort_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = MagentoService.WSDL_LOCATION;
        if (args.length > 0) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        MagentoService ss = new MagentoService(wsdlURL, SERVICE_NAME);
        MageApiModelServerWsiHandlerPortType port = ss.getMageApiModelServerWsiHandlerPort();  
        
        {
        System.out.println("Invoking catalogProductAttributeInfo...");
        CatalogProductAttributeInfoRequestParam _catalogProductAttributeInfo_parameters = null;
        CatalogProductAttributeInfoResponseParam _catalogProductAttributeInfo__return = port.catalogProductAttributeInfo(_catalogProductAttributeInfo_parameters);
        System.out.println("catalogProductAttributeInfo.result=" + _catalogProductAttributeInfo__return);


        }
        {
        System.out.println("Invoking catalogProductDelete...");
        CatalogProductDeleteRequestParam _catalogProductDelete_parameters = null;
        CatalogProductDeleteResponseParam _catalogProductDelete__return = port.catalogProductDelete(_catalogProductDelete_parameters);
        System.out.println("catalogProductDelete.result=" + _catalogProductDelete__return);


        }
        {
        System.out.println("Invoking catalogProductDownloadableLinkAdd...");
        CatalogProductDownloadableLinkAddRequestParam _catalogProductDownloadableLinkAdd_parameters = null;
        CatalogProductDownloadableLinkAddResponseParam _catalogProductDownloadableLinkAdd__return = port.catalogProductDownloadableLinkAdd(_catalogProductDownloadableLinkAdd_parameters);
        System.out.println("catalogProductDownloadableLinkAdd.result=" + _catalogProductDownloadableLinkAdd__return);


        }
        {
        System.out.println("Invoking salesOrderCreditmemoList...");
        SalesOrderCreditmemoListRequestParam _salesOrderCreditmemoList_parameters = null;
        SalesOrderCreditmemoListResponseParam _salesOrderCreditmemoList__return = port.salesOrderCreditmemoList(_salesOrderCreditmemoList_parameters);
        System.out.println("salesOrderCreditmemoList.result=" + _salesOrderCreditmemoList__return);


        }
        {
        System.out.println("Invoking catalogProductCreate...");
        CatalogProductCreateRequestParam _catalogProductCreate_parameters = null;
        CatalogProductCreateResponseParam _catalogProductCreate__return = port.catalogProductCreate(_catalogProductCreate_parameters);
        System.out.println("catalogProductCreate.result=" + _catalogProductCreate__return);


        }
        {
        System.out.println("Invoking catalogProductAttributeCurrentStore...");
        CatalogProductAttributeCurrentStoreRequestParam _catalogProductAttributeCurrentStore_parameters = null;
        CatalogProductAttributeCurrentStoreResponseParam _catalogProductAttributeCurrentStore__return = port.catalogProductAttributeCurrentStore(_catalogProductAttributeCurrentStore_parameters);
        System.out.println("catalogProductAttributeCurrentStore.result=" + _catalogProductAttributeCurrentStore__return);


        }
        {
        System.out.println("Invoking catalogProductCustomOptionValueList...");
        CatalogProductCustomOptionValueListRequestParam _catalogProductCustomOptionValueList_parameters = null;
        CatalogProductCustomOptionValueListResponseParam _catalogProductCustomOptionValueList__return = port.catalogProductCustomOptionValueList(_catalogProductCustomOptionValueList_parameters);
        System.out.println("catalogProductCustomOptionValueList.result=" + _catalogProductCustomOptionValueList__return);


        }
        {
        System.out.println("Invoking catalogCategoryAttributeCurrentStore...");
        CatalogCategoryAttributeCurrentStoreRequestParam _catalogCategoryAttributeCurrentStore_parameters = null;
        CatalogCategoryAttributeCurrentStoreResponseParam _catalogCategoryAttributeCurrentStore__return = port.catalogCategoryAttributeCurrentStore(_catalogCategoryAttributeCurrentStore_parameters);
        System.out.println("catalogCategoryAttributeCurrentStore.result=" + _catalogCategoryAttributeCurrentStore__return);


        }
        {
        System.out.println("Invoking salesOrderCancel...");
        SalesOrderCancelRequestParam _salesOrderCancel_parameters = null;
        SalesOrderCancelResponseParam _salesOrderCancel__return = port.salesOrderCancel(_salesOrderCancel_parameters);
        System.out.println("salesOrderCancel.result=" + _salesOrderCancel__return);


        }
        {
        System.out.println("Invoking resourceFaults...");
        ResourceFaultsParam _resourceFaults_parameters = null;
        ResourceFaultsResponseParam _resourceFaults__return = port.resourceFaults(_resourceFaults_parameters);
        System.out.println("resourceFaults.result=" + _resourceFaults__return);


        }
        {
        System.out.println("Invoking giftMessageSetForQuote...");
        GiftMessageForQuoteRequestParam _giftMessageSetForQuote_parameters = null;
        GiftMessageForQuoteResponseParam _giftMessageSetForQuote__return = port.giftMessageSetForQuote(_giftMessageSetForQuote_parameters);
        System.out.println("giftMessageSetForQuote.result=" + _giftMessageSetForQuote__return);


        }
        {
        System.out.println("Invoking catalogProductTypeList...");
        CatalogProductTypeListRequestParam _catalogProductTypeList_parameters = null;
        CatalogProductTypeListResponseParam _catalogProductTypeList__return = port.catalogProductTypeList(_catalogProductTypeList_parameters);
        System.out.println("catalogProductTypeList.result=" + _catalogProductTypeList__return);


        }
        {
        System.out.println("Invoking multiCall...");
        MultiCallParam _multiCall_parameters = null;
        MultiCallResponseParam _multiCall__return = port.multiCall(_multiCall_parameters);
        System.out.println("multiCall.result=" + _multiCall__return);


        }
        {
        System.out.println("Invoking catalogProductLinkList...");
        CatalogProductLinkListRequestParam _catalogProductLinkList_parameters = null;
        CatalogProductLinkListResponseParam _catalogProductLinkList__return = port.catalogProductLinkList(_catalogProductLinkList_parameters);
        System.out.println("catalogProductLinkList.result=" + _catalogProductLinkList__return);


        }
        {
        System.out.println("Invoking salesOrderShipmentGetCarriers...");
        SalesOrderShipmentGetCarriersRequestParam _salesOrderShipmentGetCarriers_parameters = null;
        SalesOrderShipmentGetCarriersResponseParam _salesOrderShipmentGetCarriers__return = port.salesOrderShipmentGetCarriers(_salesOrderShipmentGetCarriers_parameters);
        System.out.println("salesOrderShipmentGetCarriers.result=" + _salesOrderShipmentGetCarriers__return);


        }
        {
        System.out.println("Invoking catalogCategoryRemoveProduct...");
        CatalogCategoryRemoveProductRequestParam _catalogCategoryRemoveProduct_parameters = null;
        CatalogCategoryRemoveProductResponseParam _catalogCategoryRemoveProduct__return = port.catalogCategoryRemoveProduct(_catalogCategoryRemoveProduct_parameters);
        System.out.println("catalogCategoryRemoveProduct.result=" + _catalogCategoryRemoveProduct__return);


        }
        {
        System.out.println("Invoking salesOrderShipmentCreate...");
        SalesOrderShipmentCreateRequestParam _salesOrderShipmentCreate_parameters = null;
        SalesOrderShipmentCreateResponseParam _salesOrderShipmentCreate__return = port.salesOrderShipmentCreate(_salesOrderShipmentCreate_parameters);
        System.out.println("salesOrderShipmentCreate.result=" + _salesOrderShipmentCreate__return);


        }
        {
        System.out.println("Invoking salesOrderInfo...");
        SalesOrderInfoRequestParam _salesOrderInfo_parameters = null;
        SalesOrderInfoResponseParam _salesOrderInfo__return = port.salesOrderInfo(_salesOrderInfo_parameters);
        System.out.println("salesOrderInfo.result=" + _salesOrderInfo__return);


        }
        {
        System.out.println("Invoking catalogProductLinkUpdate...");
        CatalogProductLinkUpdateRequestParam _catalogProductLinkUpdate_parameters = null;
        CatalogProductLinkUpdateResponseParam _catalogProductLinkUpdate__return = port.catalogProductLinkUpdate(_catalogProductLinkUpdate_parameters);
        System.out.println("catalogProductLinkUpdate.result=" + _catalogProductLinkUpdate__return);


        }
        {
        System.out.println("Invoking shoppingCartProductUpdate...");
        ShoppingCartProductUpdateRequestParam _shoppingCartProductUpdate_parameters = null;
        ShoppingCartProductUpdateResponseParam _shoppingCartProductUpdate__return = port.shoppingCartProductUpdate(_shoppingCartProductUpdate_parameters);
        System.out.println("shoppingCartProductUpdate.result=" + _shoppingCartProductUpdate__return);


        }
        {
        System.out.println("Invoking catalogCategoryCurrentStore...");
        CatalogCategoryCurrentStoreRequestParam _catalogCategoryCurrentStore_parameters = null;
        CatalogCategoryCurrentStoreResponseParam _catalogCategoryCurrentStore__return = port.catalogCategoryCurrentStore(_catalogCategoryCurrentStore_parameters);
        System.out.println("catalogCategoryCurrentStore.result=" + _catalogCategoryCurrentStore__return);


        }
        {
        System.out.println("Invoking customerAddressCreate...");
        CustomerAddressCreateRequestParam _customerAddressCreate_parameters = null;
        CustomerAddressCreateResponseParam _customerAddressCreate__return = port.customerAddressCreate(_customerAddressCreate_parameters);
        System.out.println("customerAddressCreate.result=" + _customerAddressCreate__return);


        }
        {
        System.out.println("Invoking catalogCategoryAttributeOptions...");
        CatalogCategoryAttributeOptionsRequestParam _catalogCategoryAttributeOptions_parameters = null;
        CatalogCategoryAttributeOptionsResponseParam _catalogCategoryAttributeOptions__return = port.catalogCategoryAttributeOptions(_catalogCategoryAttributeOptions_parameters);
        System.out.println("catalogCategoryAttributeOptions.result=" + _catalogCategoryAttributeOptions__return);


        }
        {
        System.out.println("Invoking catalogProductAttributeSetRemove...");
        CatalogProductAttributeSetRemoveRequestParam _catalogProductAttributeSetRemove_parameters = null;
        CatalogProductAttributeSetRemoveResponseParam _catalogProductAttributeSetRemove__return = port.catalogProductAttributeSetRemove(_catalogProductAttributeSetRemove_parameters);
        System.out.println("catalogProductAttributeSetRemove.result=" + _catalogProductAttributeSetRemove__return);


        }
        {
        System.out.println("Invoking catalogProductAttributeOptions...");
        CatalogProductAttributeOptionsRequestParam _catalogProductAttributeOptions_parameters = null;
        CatalogProductAttributeOptionsResponseParam _catalogProductAttributeOptions__return = port.catalogProductAttributeOptions(_catalogProductAttributeOptions_parameters);
        System.out.println("catalogProductAttributeOptions.result=" + _catalogProductAttributeOptions__return);


        }
        {
        System.out.println("Invoking salesOrderCreditmemoInfo...");
        SalesOrderCreditmemoInfoRequestParam _salesOrderCreditmemoInfo_parameters = null;
        SalesOrderCreditmemoInfoResponseParam _salesOrderCreditmemoInfo__return = port.salesOrderCreditmemoInfo(_salesOrderCreditmemoInfo_parameters);
        System.out.println("salesOrderCreditmemoInfo.result=" + _salesOrderCreditmemoInfo__return);


        }
        {
        System.out.println("Invoking salesOrderShipmentInfo...");
        SalesOrderShipmentInfoRequestParam _salesOrderShipmentInfo_parameters = null;
        SalesOrderShipmentInfoResponseParam _salesOrderShipmentInfo__return = port.salesOrderShipmentInfo(_salesOrderShipmentInfo_parameters);
        System.out.println("salesOrderShipmentInfo.result=" + _salesOrderShipmentInfo__return);


        }
        {
        System.out.println("Invoking globalFaults...");
        GlobalFaultsParam _globalFaults_parameters = null;
        GlobalFaultsResponseParam _globalFaults__return = port.globalFaults(_globalFaults_parameters);
        System.out.println("globalFaults.result=" + _globalFaults__return);


        }
        {
        System.out.println("Invoking shoppingCartShippingMethod...");
        ShoppingCartShippingMethodRequestParam _shoppingCartShippingMethod_parameters = null;
        ShoppingCartShippingMethodResponseParam _shoppingCartShippingMethod__return = port.shoppingCartShippingMethod(_shoppingCartShippingMethod_parameters);
        System.out.println("shoppingCartShippingMethod.result=" + _shoppingCartShippingMethod__return);


        }
        {
        System.out.println("Invoking catalogCategoryUpdate...");
        CatalogCategoryUpdateRequestParam _catalogCategoryUpdate_parameters = null;
        CatalogCategoryUpdateResponseParam _catalogCategoryUpdate__return = port.catalogCategoryUpdate(_catalogCategoryUpdate_parameters);
        System.out.println("catalogCategoryUpdate.result=" + _catalogCategoryUpdate__return);


        }
        {
        System.out.println("Invoking catalogCategoryDelete...");
        CatalogCategoryDeleteRequestParam _catalogCategoryDelete_parameters = null;
        CatalogCategoryDeleteResponseParam _catalogCategoryDelete__return = port.catalogCategoryDelete(_catalogCategoryDelete_parameters);
        System.out.println("catalogCategoryDelete.result=" + _catalogCategoryDelete__return);


        }
        {
        System.out.println("Invoking catalogProductAttributeMediaCreate...");
        CatalogProductAttributeMediaCreateRequestParam _catalogProductAttributeMediaCreate_parameters = null;
        CatalogProductAttributeMediaCreateResponseParam _catalogProductAttributeMediaCreate__return = port.catalogProductAttributeMediaCreate(_catalogProductAttributeMediaCreate_parameters);
        System.out.println("catalogProductAttributeMediaCreate.result=" + _catalogProductAttributeMediaCreate__return);


        }
        {
        System.out.println("Invoking catalogProductAttributeUpdate...");
        CatalogProductAttributeUpdateRequestParam _catalogProductAttributeUpdate_parameters = null;
        CatalogProductAttributeUpdateResponseParam _catalogProductAttributeUpdate__return = port.catalogProductAttributeUpdate(_catalogProductAttributeUpdate_parameters);
        System.out.println("catalogProductAttributeUpdate.result=" + _catalogProductAttributeUpdate__return);


        }
        {
        System.out.println("Invoking catalogInventoryStockItemList...");
        CatalogInventoryStockItemListRequestParam _catalogInventoryStockItemList_parameters = null;
        CatalogInventoryStockItemListResponseParam _catalogInventoryStockItemList__return = port.catalogInventoryStockItemList(_catalogInventoryStockItemList_parameters);
        System.out.println("catalogInventoryStockItemList.result=" + _catalogInventoryStockItemList__return);


        }
        {
        System.out.println("Invoking shoppingCartCreate...");
        ShoppingCartCreateRequestParam _shoppingCartCreate_parameters = null;
        ShoppingCartCreateResponseParam _shoppingCartCreate__return = port.shoppingCartCreate(_shoppingCartCreate_parameters);
        System.out.println("shoppingCartCreate.result=" + _shoppingCartCreate__return);


        }
        {
        System.out.println("Invoking catalogProductDownloadableLinkList...");
        CatalogProductDownloadableLinkListRequestParam _catalogProductDownloadableLinkList_parameters = null;
        CatalogProductDownloadableLinkListResponseParam _catalogProductDownloadableLinkList__return = port.catalogProductDownloadableLinkList(_catalogProductDownloadableLinkList_parameters);
        System.out.println("catalogProductDownloadableLinkList.result=" + _catalogProductDownloadableLinkList__return);


        }
        {
        System.out.println("Invoking storeInfo...");
        StoreInfoRequestParam _storeInfo_parameters = null;
        StoreInfoResponseParam _storeInfo__return = port.storeInfo(_storeInfo_parameters);
        System.out.println("storeInfo.result=" + _storeInfo__return);


        }
        {
        System.out.println("Invoking catalogProductAttributeMediaTypes...");
        CatalogProductAttributeMediaTypesRequestParam _catalogProductAttributeMediaTypes_parameters = null;
        CatalogProductAttributeMediaTypesResponseParam _catalogProductAttributeMediaTypes__return = port.catalogProductAttributeMediaTypes(_catalogProductAttributeMediaTypes_parameters);
        System.out.println("catalogProductAttributeMediaTypes.result=" + _catalogProductAttributeMediaTypes__return);


        }
        {
        System.out.println("Invoking customerCustomerList...");
        CustomerCustomerListRequestParam _customerCustomerList_parameters = null;
        CustomerCustomerListResponseParam _customerCustomerList__return = port.customerCustomerList(_customerCustomerList_parameters);
        System.out.println("customerCustomerList.result=" + _customerCustomerList__return);


        }
        {
        System.out.println("Invoking directoryCountryList...");
        DirectoryCountryListRequestParam _directoryCountryList_parameters = null;
        DirectoryCountryListResponseParam _directoryCountryList__return = port.directoryCountryList(_directoryCountryList_parameters);
        System.out.println("directoryCountryList.result=" + _directoryCountryList__return);


        }
        {
        System.out.println("Invoking storeList...");
        StoreListRequestParam _storeList_parameters = null;
        StoreListResponseParam _storeList__return = port.storeList(_storeList_parameters);
        System.out.println("storeList.result=" + _storeList__return);


        }
        {
        System.out.println("Invoking salesOrderInvoiceInfo...");
        SalesOrderInvoiceInfoRequestParam _salesOrderInvoiceInfo_parameters = null;
        SalesOrderInvoiceInfoResponseParam _salesOrderInvoiceInfo__return = port.salesOrderInvoiceInfo(_salesOrderInvoiceInfo_parameters);
        System.out.println("salesOrderInvoiceInfo.result=" + _salesOrderInvoiceInfo__return);


        }
        {
        System.out.println("Invoking catalogInventoryStockItemMultiUpdate...");
        CatalogInventoryStockItemMultiUpdateRequestParam _catalogInventoryStockItemMultiUpdate_parameters = null;
        CatalogInventoryStockItemMultiUpdateResponseParam _catalogInventoryStockItemMultiUpdate__return = port.catalogInventoryStockItemMultiUpdate(_catalogInventoryStockItemMultiUpdate_parameters);
        System.out.println("catalogInventoryStockItemMultiUpdate.result=" + _catalogInventoryStockItemMultiUpdate__return);


        }
        {
        System.out.println("Invoking catalogProductCustomOptionValueUpdate...");
        CatalogProductCustomOptionValueUpdateRequestParam _catalogProductCustomOptionValueUpdate_parameters = null;
        CatalogProductCustomOptionValueUpdateResponseParam _catalogProductCustomOptionValueUpdate__return = port.catalogProductCustomOptionValueUpdate(_catalogProductCustomOptionValueUpdate_parameters);
        System.out.println("catalogProductCustomOptionValueUpdate.result=" + _catalogProductCustomOptionValueUpdate__return);


        }
        {
        System.out.println("Invoking catalogProductTagRemove...");
        CatalogProductTagRemoveRequestParam _catalogProductTagRemove_parameters = null;
        CatalogProductTagRemoveResponseParam _catalogProductTagRemove__return = port.catalogProductTagRemove(_catalogProductTagRemove_parameters);
        System.out.println("catalogProductTagRemove.result=" + _catalogProductTagRemove__return);


        }
        {
        System.out.println("Invoking customerAddressDelete...");
        CustomerAddressDeleteRequestParam _customerAddressDelete_parameters = null;
        CustomerAddressDeleteResponseParam _customerAddressDelete__return = port.customerAddressDelete(_customerAddressDelete_parameters);
        System.out.println("customerAddressDelete.result=" + _customerAddressDelete__return);


        }
        {
        System.out.println("Invoking startSession...");
        StartSessionResponseParam _startSession__return = port.startSession();
        System.out.println("startSession.result=" + _startSession__return);


        }
        {
        System.out.println("Invoking salesOrderList...");
        SalesOrderListRequestParam _salesOrderList_parameters = null;
        SalesOrderListResponseParam _salesOrderList__return = port.salesOrderList(_salesOrderList_parameters);
        System.out.println("salesOrderList.result=" + _salesOrderList__return);


        }
        {
        System.out.println("Invoking catalogProductCustomOptionValueAdd...");
        CatalogProductCustomOptionValueAddRequestParam _catalogProductCustomOptionValueAdd_parameters = null;
        CatalogProductCustomOptionValueAddResponseParam _catalogProductCustomOptionValueAdd__return = port.catalogProductCustomOptionValueAdd(_catalogProductCustomOptionValueAdd_parameters);
        System.out.println("catalogProductCustomOptionValueAdd.result=" + _catalogProductCustomOptionValueAdd__return);


        }
        {
        System.out.println("Invoking catalogCategoryUpdateProduct...");
        CatalogCategoryUpdateProductRequestParam _catalogCategoryUpdateProduct_parameters = null;
        CatalogCategoryUpdateProductResponseParam _catalogCategoryUpdateProduct__return = port.catalogCategoryUpdateProduct(_catalogCategoryUpdateProduct_parameters);
        System.out.println("catalogCategoryUpdateProduct.result=" + _catalogCategoryUpdateProduct__return);


        }
        {
        System.out.println("Invoking shoppingCartCustomerSet...");
        ShoppingCartCustomerSetRequestParam _shoppingCartCustomerSet_parameters = null;
        ShoppingCartCustomerSetResponseParam _shoppingCartCustomerSet__return = port.shoppingCartCustomerSet(_shoppingCartCustomerSet_parameters);
        System.out.println("shoppingCartCustomerSet.result=" + _shoppingCartCustomerSet__return);


        }
        {
        System.out.println("Invoking salesOrderShipmentRemoveTrack...");
        SalesOrderShipmentRemoveTrackRequestParam _salesOrderShipmentRemoveTrack_parameters = null;
        SalesOrderShipmentRemoveTrackResponseParam _salesOrderShipmentRemoveTrack__return = port.salesOrderShipmentRemoveTrack(_salesOrderShipmentRemoveTrack_parameters);
        System.out.println("salesOrderShipmentRemoveTrack.result=" + _salesOrderShipmentRemoveTrack__return);


        }
        {
        System.out.println("Invoking catalogCategoryTree...");
        CatalogCategoryTreeRequestParam _catalogCategoryTree_parameters = null;
        CatalogCategoryTreeResponseParam _catalogCategoryTree__return = port.catalogCategoryTree(_catalogCategoryTree_parameters);
        System.out.println("catalogCategoryTree.result=" + _catalogCategoryTree__return);


        }
        {
        System.out.println("Invoking catalogProductAttributeList...");
        CatalogProductAttributeListRequestParam _catalogProductAttributeList_parameters = null;
        CatalogProductAttributeListResponseParam _catalogProductAttributeList__return = port.catalogProductAttributeList(_catalogProductAttributeList_parameters);
        System.out.println("catalogProductAttributeList.result=" + _catalogProductAttributeList__return);


        }
        {
        System.out.println("Invoking catalogProductLinkAssign...");
        CatalogProductLinkAssignRequestParam _catalogProductLinkAssign_parameters = null;
        CatalogProductLinkAssignResponseParam _catalogProductLinkAssign__return = port.catalogProductLinkAssign(_catalogProductLinkAssign_parameters);
        System.out.println("catalogProductLinkAssign.result=" + _catalogProductLinkAssign__return);


        }
        {
        System.out.println("Invoking catalogCategoryAssignProduct...");
        CatalogCategoryAssignProductRequestParam _catalogCategoryAssignProduct_parameters = null;
        CatalogCategoryAssignProductResponseParam _catalogCategoryAssignProduct__return = port.catalogCategoryAssignProduct(_catalogCategoryAssignProduct_parameters);
        System.out.println("catalogCategoryAssignProduct.result=" + _catalogCategoryAssignProduct__return);


        }
        {
        System.out.println("Invoking catalogCategoryCreate...");
        CatalogCategoryCreateRequestParam _catalogCategoryCreate_parameters = null;
        CatalogCategoryCreateResponseParam _catalogCategoryCreate__return = port.catalogCategoryCreate(_catalogCategoryCreate_parameters);
        System.out.println("catalogCategoryCreate.result=" + _catalogCategoryCreate__return);


        }
        {
        System.out.println("Invoking shoppingCartOrder...");
        ShoppingCartOrderRequestParam _shoppingCartOrder_parameters = null;
        ShoppingCartOrderResponseParam _shoppingCartOrder__return = port.shoppingCartOrder(_shoppingCartOrder_parameters);
        System.out.println("shoppingCartOrder.result=" + _shoppingCartOrder__return);


        }
        {
        System.out.println("Invoking catalogProductCustomOptionUpdate...");
        CatalogProductCustomOptionUpdateRequestParam _catalogProductCustomOptionUpdate_parameters = null;
        CatalogProductCustomOptionUpdateResponseParam _catalogProductCustomOptionUpdate__return = port.catalogProductCustomOptionUpdate(_catalogProductCustomOptionUpdate_parameters);
        System.out.println("catalogProductCustomOptionUpdate.result=" + _catalogProductCustomOptionUpdate__return);


        }
        {
        System.out.println("Invoking catalogProductCustomOptionList...");
        CatalogProductCustomOptionListRequestParam _catalogProductCustomOptionList_parameters = null;
        CatalogProductCustomOptionListResponseParam _catalogProductCustomOptionList__return = port.catalogProductCustomOptionList(_catalogProductCustomOptionList_parameters);
        System.out.println("catalogProductCustomOptionList.result=" + _catalogProductCustomOptionList__return);


        }
        {
        System.out.println("Invoking customerAddressUpdate...");
        CustomerAddressUpdateRequestParam _customerAddressUpdate_parameters = null;
        CustomerAddressUpdateResponseParam _customerAddressUpdate__return = port.customerAddressUpdate(_customerAddressUpdate_parameters);
        System.out.println("customerAddressUpdate.result=" + _customerAddressUpdate__return);


        }
        {
        System.out.println("Invoking catalogProductAttributeSetGroupRename...");
        CatalogProductAttributeSetGroupRenameRequestParam _catalogProductAttributeSetGroupRename_parameters = null;
        CatalogProductAttributeSetGroupRenameResponseParam _catalogProductAttributeSetGroupRename__return = port.catalogProductAttributeSetGroupRename(_catalogProductAttributeSetGroupRename_parameters);
        System.out.println("catalogProductAttributeSetGroupRename.result=" + _catalogProductAttributeSetGroupRename__return);


        }
        {
        System.out.println("Invoking shoppingCartTotals...");
        ShoppingCartTotalsRequestParam _shoppingCartTotals_parameters = null;
        ShoppingCartTotalsResponseParam _shoppingCartTotals__return = port.shoppingCartTotals(_shoppingCartTotals_parameters);
        System.out.println("shoppingCartTotals.result=" + _shoppingCartTotals__return);


        }
        {
        System.out.println("Invoking catalogInventoryStockItemUpdate...");
        CatalogInventoryStockItemUpdateRequestParam _catalogInventoryStockItemUpdate_parameters = null;
        CatalogInventoryStockItemUpdateResponseParam _catalogInventoryStockItemUpdate__return = port.catalogInventoryStockItemUpdate(_catalogInventoryStockItemUpdate_parameters);
        System.out.println("catalogInventoryStockItemUpdate.result=" + _catalogInventoryStockItemUpdate__return);


        }
        {
        System.out.println("Invoking catalogCategoryAttributeList...");
        CatalogCategoryAttributeListRequestParam _catalogCategoryAttributeList_parameters = null;
        CatalogCategoryAttributeListResponseParam _catalogCategoryAttributeList__return = port.catalogCategoryAttributeList(_catalogCategoryAttributeList_parameters);
        System.out.println("catalogCategoryAttributeList.result=" + _catalogCategoryAttributeList__return);


        }
        {
        System.out.println("Invoking catalogProductDownloadableLinkRemove...");
        CatalogProductDownloadableLinkRemoveRequestParam _catalogProductDownloadableLinkRemove_parameters = null;
        CatalogProductDownloadableLinkRemoveResponseParam _catalogProductDownloadableLinkRemove__return = port.catalogProductDownloadableLinkRemove(_catalogProductDownloadableLinkRemove_parameters);
        System.out.println("catalogProductDownloadableLinkRemove.result=" + _catalogProductDownloadableLinkRemove__return);


        }
        {
        System.out.println("Invoking catalogProductCustomOptionAdd...");
        CatalogProductCustomOptionAddRequestParam _catalogProductCustomOptionAdd_parameters = null;
        CatalogProductCustomOptionAddResponseParam _catalogProductCustomOptionAdd__return = port.catalogProductCustomOptionAdd(_catalogProductCustomOptionAdd_parameters);
        System.out.println("catalogProductCustomOptionAdd.result=" + _catalogProductCustomOptionAdd__return);


        }
        {
        System.out.println("Invoking catalogProductList...");
        CatalogProductListRequestParam _catalogProductList_parameters = null;
        CatalogProductListResponseParam _catalogProductList__return = port.catalogProductList(_catalogProductList_parameters);
        System.out.println("catalogProductList.result=" + _catalogProductList__return);


        }
        {
        System.out.println("Invoking catalogProductAttributeMediaUpdate...");
        CatalogProductAttributeMediaUpdateRequestParam _catalogProductAttributeMediaUpdate_parameters = null;
        CatalogProductAttributeMediaUpdateResponseParam _catalogProductAttributeMediaUpdate__return = port.catalogProductAttributeMediaUpdate(_catalogProductAttributeMediaUpdate_parameters);
        System.out.println("catalogProductAttributeMediaUpdate.result=" + _catalogProductAttributeMediaUpdate__return);


        }
        {
        System.out.println("Invoking login...");
        LoginParam _login_parameters = null;
        LoginResponseParam _login__return = port.login(_login_parameters);
        System.out.println("login.result=" + _login__return);


        }
        {
        System.out.println("Invoking customerGroupList...");
        CustomerGroupListRequestParam _customerGroupList_parameters = null;
        CustomerGroupListResponseParam _customerGroupList__return = port.customerGroupList(_customerGroupList_parameters);
        System.out.println("customerGroupList.result=" + _customerGroupList__return);


        }
        {
        System.out.println("Invoking catalogProductAttributeSetGroupAdd...");
        CatalogProductAttributeSetGroupAddRequestParam _catalogProductAttributeSetGroupAdd_parameters = null;
        CatalogProductAttributeSetGroupAddResponseParam _catalogProductAttributeSetGroupAdd__return = port.catalogProductAttributeSetGroupAdd(_catalogProductAttributeSetGroupAdd_parameters);
        System.out.println("catalogProductAttributeSetGroupAdd.result=" + _catalogProductAttributeSetGroupAdd__return);


        }
        {
        System.out.println("Invoking customerCustomerInfo...");
        CustomerCustomerInfoRequestParam _customerCustomerInfo_parameters = null;
        CustomerCustomerInfoResponseParam _customerCustomerInfo__return = port.customerCustomerInfo(_customerCustomerInfo_parameters);
        System.out.println("customerCustomerInfo.result=" + _customerCustomerInfo__return);


        }
        {
        System.out.println("Invoking shoppingCartInfo...");
        ShoppingCartInfoRequestParam _shoppingCartInfo_parameters = null;
        ShoppingCartInfoResponseParam _shoppingCartInfo__return = port.shoppingCartInfo(_shoppingCartInfo_parameters);
        System.out.println("shoppingCartInfo.result=" + _shoppingCartInfo__return);


        }
        {
        System.out.println("Invoking catalogProductAttributeMediaRemove...");
        CatalogProductAttributeMediaRemoveRequestParam _catalogProductAttributeMediaRemove_parameters = null;
        CatalogProductAttributeMediaRemoveResponseParam _catalogProductAttributeMediaRemove__return = port.catalogProductAttributeMediaRemove(_catalogProductAttributeMediaRemove_parameters);
        System.out.println("catalogProductAttributeMediaRemove.result=" + _catalogProductAttributeMediaRemove__return);


        }
        {
        System.out.println("Invoking salesOrderCreditmemoCancel...");
        SalesOrderCreditmemoCancelRequestParam _salesOrderCreditmemoCancel_parameters = null;
        SalesOrderCreditmemoCancelResponseParam _salesOrderCreditmemoCancel__return = port.salesOrderCreditmemoCancel(_salesOrderCreditmemoCancel_parameters);
        System.out.println("salesOrderCreditmemoCancel.result=" + _salesOrderCreditmemoCancel__return);


        }
        {
        System.out.println("Invoking customerAddressList...");
        CustomerAddressListRequestParam _customerAddressList_parameters = null;
        CustomerAddressListResponseParam _customerAddressList__return = port.customerAddressList(_customerAddressList_parameters);
        System.out.println("customerAddressList.result=" + _customerAddressList__return);


        }
        {
        System.out.println("Invoking shoppingCartProductAdd...");
        ShoppingCartProductAddRequestParam _shoppingCartProductAdd_parameters = null;
        ShoppingCartProductAddResponseParam _shoppingCartProductAdd__return = port.shoppingCartProductAdd(_shoppingCartProductAdd_parameters);
        System.out.println("shoppingCartProductAdd.result=" + _shoppingCartProductAdd__return);


        }
        {
        System.out.println("Invoking catalogProductGetSpecialPrice...");
        CatalogProductGetSpecialPriceRequestParam _catalogProductGetSpecialPrice_parameters = null;
        CatalogProductGetSpecialPriceResponseParam _catalogProductGetSpecialPrice__return = port.catalogProductGetSpecialPrice(_catalogProductGetSpecialPrice_parameters);
        System.out.println("catalogProductGetSpecialPrice.result=" + _catalogProductGetSpecialPrice__return);


        }
        {
        System.out.println("Invoking endSession...");
        EndSessionParam _endSession_parameters = null;
        EndSessionResponseParam _endSession__return = port.endSession(_endSession_parameters);
        System.out.println("endSession.result=" + _endSession__return);


        }
        {
        System.out.println("Invoking salesOrderCreditmemoCreate...");
        SalesOrderCreditmemoCreateRequestParam _salesOrderCreditmemoCreate_parameters = null;
        SalesOrderCreditmemoCreateResponseParam _salesOrderCreditmemoCreate__return = port.salesOrderCreditmemoCreate(_salesOrderCreditmemoCreate_parameters);
        System.out.println("salesOrderCreditmemoCreate.result=" + _salesOrderCreditmemoCreate__return);


        }
        {
        System.out.println("Invoking shoppingCartPaymentList...");
        ShoppingCartPaymentListRequestParam _shoppingCartPaymentList_parameters = null;
        ShoppingCartPaymentListResponseParam _shoppingCartPaymentList__return = port.shoppingCartPaymentList(_shoppingCartPaymentList_parameters);
        System.out.println("shoppingCartPaymentList.result=" + _shoppingCartPaymentList__return);


        }
        {
        System.out.println("Invoking catalogProductTagInfo...");
        CatalogProductTagInfoRequestParam _catalogProductTagInfo_parameters = null;
        CatalogProductTagInfoResponseParam _catalogProductTagInfo__return = port.catalogProductTagInfo(_catalogProductTagInfo_parameters);
        System.out.println("catalogProductTagInfo.result=" + _catalogProductTagInfo__return);


        }
        {
        System.out.println("Invoking salesOrderInvoiceAddComment...");
        SalesOrderInvoiceAddCommentRequestParam _salesOrderInvoiceAddComment_parameters = null;
        SalesOrderInvoiceAddCommentResponseParam _salesOrderInvoiceAddComment__return = port.salesOrderInvoiceAddComment(_salesOrderInvoiceAddComment_parameters);
        System.out.println("salesOrderInvoiceAddComment.result=" + _salesOrderInvoiceAddComment__return);


        }
        {
        System.out.println("Invoking magentoInfo...");
        MagentoInfoRequestParam _magentoInfo_parameters = null;
        MagentoInfoResponseParam _magentoInfo__return = port.magentoInfo(_magentoInfo_parameters);
        System.out.println("magentoInfo.result=" + _magentoInfo__return);


        }
        {
        System.out.println("Invoking customerCustomerUpdate...");
        CustomerCustomerUpdateRequestParam _customerCustomerUpdate_parameters = null;
        CustomerCustomerUpdateResponseParam _customerCustomerUpdate__return = port.customerCustomerUpdate(_customerCustomerUpdate_parameters);
        System.out.println("customerCustomerUpdate.result=" + _customerCustomerUpdate__return);


        }
        {
        System.out.println("Invoking catalogProductInfo...");
        CatalogProductInfoRequestParam _catalogProductInfo_parameters = null;
        CatalogProductInfoResponseParam _catalogProductInfo__return = port.catalogProductInfo(_catalogProductInfo_parameters);
        System.out.println("catalogProductInfo.result=" + _catalogProductInfo__return);


        }
        {
        System.out.println("Invoking catalogProductTagUpdate...");
        CatalogProductTagUpdateRequestParam _catalogProductTagUpdate_parameters = null;
        CatalogProductTagUpdateResponseParam _catalogProductTagUpdate__return = port.catalogProductTagUpdate(_catalogProductTagUpdate_parameters);
        System.out.println("catalogProductTagUpdate.result=" + _catalogProductTagUpdate__return);


        }
        {
        System.out.println("Invoking catalogProductAttributeRemove...");
        CatalogProductAttributeRemoveRequestParam _catalogProductAttributeRemove_parameters = null;
        CatalogProductAttributeRemoveResponseParam _catalogProductAttributeRemove__return = port.catalogProductAttributeRemove(_catalogProductAttributeRemove_parameters);
        System.out.println("catalogProductAttributeRemove.result=" + _catalogProductAttributeRemove__return);


        }
        {
        System.out.println("Invoking salesOrderShipmentList...");
        SalesOrderShipmentListRequestParam _salesOrderShipmentList_parameters = null;
        SalesOrderShipmentListResponseParam _salesOrderShipmentList__return = port.salesOrderShipmentList(_salesOrderShipmentList_parameters);
        System.out.println("salesOrderShipmentList.result=" + _salesOrderShipmentList__return);


        }
        {
        System.out.println("Invoking catalogProductAttributeSetCreate...");
        CatalogProductAttributeSetCreateRequestParam _catalogProductAttributeSetCreate_parameters = null;
        CatalogProductAttributeSetCreateResponseParam _catalogProductAttributeSetCreate__return = port.catalogProductAttributeSetCreate(_catalogProductAttributeSetCreate_parameters);
        System.out.println("catalogProductAttributeSetCreate.result=" + _catalogProductAttributeSetCreate__return);


        }
        {
        System.out.println("Invoking catalogProductCustomOptionTypes...");
        CatalogProductCustomOptionTypesRequestParam _catalogProductCustomOptionTypes_parameters = null;
        CatalogProductCustomOptionTypesResponseParam _catalogProductCustomOptionTypes__return = port.catalogProductCustomOptionTypes(_catalogProductCustomOptionTypes_parameters);
        System.out.println("catalogProductCustomOptionTypes.result=" + _catalogProductCustomOptionTypes__return);


        }
        {
        System.out.println("Invoking customerCustomerCreate...");
        CustomerCustomerCreateRequestParam _customerCustomerCreate_parameters = null;
        CustomerCustomerCreateResponseParam _customerCustomerCreate__return = port.customerCustomerCreate(_customerCustomerCreate_parameters);
        System.out.println("customerCustomerCreate.result=" + _customerCustomerCreate__return);


        }
        {
        System.out.println("Invoking catalogProductTagList...");
        CatalogProductTagListRequestParam _catalogProductTagList_parameters = null;
        CatalogProductTagListResponseParam _catalogProductTagList__return = port.catalogProductTagList(_catalogProductTagList_parameters);
        System.out.println("catalogProductTagList.result=" + _catalogProductTagList__return);


        }
        {
        System.out.println("Invoking catalogProductAttributeMediaInfo...");
        CatalogProductAttributeMediaInfoRequestParam _catalogProductAttributeMediaInfo_parameters = null;
        CatalogProductAttributeMediaInfoResponseParam _catalogProductAttributeMediaInfo__return = port.catalogProductAttributeMediaInfo(_catalogProductAttributeMediaInfo_parameters);
        System.out.println("catalogProductAttributeMediaInfo.result=" + _catalogProductAttributeMediaInfo__return);


        }
        {
        System.out.println("Invoking salesOrderCreditmemoAddComment...");
        SalesOrderCreditmemoAddCommentRequestParam _salesOrderCreditmemoAddComment_parameters = null;
        SalesOrderCreditmemoAddCommentResponseParam _salesOrderCreditmemoAddComment__return = port.salesOrderCreditmemoAddComment(_salesOrderCreditmemoAddComment_parameters);
        System.out.println("salesOrderCreditmemoAddComment.result=" + _salesOrderCreditmemoAddComment__return);


        }
        {
        System.out.println("Invoking catalogProductAttributeSetGroupRemove...");
        CatalogProductAttributeSetGroupRemoveRequestParam _catalogProductAttributeSetGroupRemove_parameters = null;
        CatalogProductAttributeSetGroupRemoveResponseParam _catalogProductAttributeSetGroupRemove__return = port.catalogProductAttributeSetGroupRemove(_catalogProductAttributeSetGroupRemove_parameters);
        System.out.println("catalogProductAttributeSetGroupRemove.result=" + _catalogProductAttributeSetGroupRemove__return);


        }
        {
        System.out.println("Invoking catalogProductUpdate...");
        CatalogProductUpdateRequestParam _catalogProductUpdate_parameters = null;
        CatalogProductUpdateResponseParam _catalogProductUpdate__return = port.catalogProductUpdate(_catalogProductUpdate_parameters);
        System.out.println("catalogProductUpdate.result=" + _catalogProductUpdate__return);


        }
        {
        System.out.println("Invoking call...");
        CallParam _call_parameters = null;
        CallResponseParam _call__return = port.call(_call_parameters);
        System.out.println("call.result=" + _call__return);


        }
        {
        System.out.println("Invoking catalogProductCustomOptionInfo...");
        CatalogProductCustomOptionInfoRequestParam _catalogProductCustomOptionInfo_parameters = null;
        CatalogProductCustomOptionInfoResponseParam _catalogProductCustomOptionInfo__return = port.catalogProductCustomOptionInfo(_catalogProductCustomOptionInfo_parameters);
        System.out.println("catalogProductCustomOptionInfo.result=" + _catalogProductCustomOptionInfo__return);


        }
        {
        System.out.println("Invoking salesOrderInvoiceCancel...");
        SalesOrderInvoiceCancelRequestParam _salesOrderInvoiceCancel_parameters = null;
        SalesOrderInvoiceCancelResponseParam _salesOrderInvoiceCancel__return = port.salesOrderInvoiceCancel(_salesOrderInvoiceCancel_parameters);
        System.out.println("salesOrderInvoiceCancel.result=" + _salesOrderInvoiceCancel__return);


        }
        {
        System.out.println("Invoking salesOrderInvoiceCreate...");
        SalesOrderInvoiceCreateRequestParam _salesOrderInvoiceCreate_parameters = null;
        SalesOrderInvoiceCreateResponseParam _salesOrderInvoiceCreate__return = port.salesOrderInvoiceCreate(_salesOrderInvoiceCreate_parameters);
        System.out.println("salesOrderInvoiceCreate.result=" + _salesOrderInvoiceCreate__return);


        }
        {
        System.out.println("Invoking directoryRegionList...");
        DirectoryRegionListRequestParam _directoryRegionList_parameters = null;
        DirectoryRegionListResponseParam _directoryRegionList__return = port.directoryRegionList(_directoryRegionList_parameters);
        System.out.println("directoryRegionList.result=" + _directoryRegionList__return);


        }
        {
        System.out.println("Invoking catalogProductLinkAttributes...");
        CatalogProductLinkAttributesRequestParam _catalogProductLinkAttributes_parameters = null;
        CatalogProductLinkAttributesResponseParam _catalogProductLinkAttributes__return = port.catalogProductLinkAttributes(_catalogProductLinkAttributes_parameters);
        System.out.println("catalogProductLinkAttributes.result=" + _catalogProductLinkAttributes__return);


        }
        {
        System.out.println("Invoking shoppingCartProductMoveToCustomerQuote...");
        ShoppingCartProductMoveToCustomerQuoteRequestParam _shoppingCartProductMoveToCustomerQuote_parameters = null;
        ShoppingCartProductMoveToCustomerQuoteResponseParam _shoppingCartProductMoveToCustomerQuote__return = port.shoppingCartProductMoveToCustomerQuote(_shoppingCartProductMoveToCustomerQuote_parameters);
        System.out.println("shoppingCartProductMoveToCustomerQuote.result=" + _shoppingCartProductMoveToCustomerQuote__return);


        }
        {
        System.out.println("Invoking catalogProductCurrentStore...");
        CatalogProductCurrentStoreRequestParam _catalogProductCurrentStore_parameters = null;
        CatalogProductCurrentStoreResponseParam _catalogProductCurrentStore__return = port.catalogProductCurrentStore(_catalogProductCurrentStore_parameters);
        System.out.println("catalogProductCurrentStore.result=" + _catalogProductCurrentStore__return);


        }
        {
        System.out.println("Invoking customerAddressInfo...");
        CustomerAddressInfoRequestParam _customerAddressInfo_parameters = null;
        CustomerAddressInfoResponseParam _customerAddressInfo__return = port.customerAddressInfo(_customerAddressInfo_parameters);
        System.out.println("customerAddressInfo.result=" + _customerAddressInfo__return);


        }
        {
        System.out.println("Invoking customerCustomerDelete...");
        CustomerCustomerDeleteRequestParam _customerCustomerDelete_parameters = null;
        CustomerCustomerDeleteResponseParam _customerCustomerDelete__return = port.customerCustomerDelete(_customerCustomerDelete_parameters);
        System.out.println("customerCustomerDelete.result=" + _customerCustomerDelete__return);


        }
        {
        System.out.println("Invoking catalogProductCustomOptionValueInfo...");
        CatalogProductCustomOptionValueInfoRequestParam _catalogProductCustomOptionValueInfo_parameters = null;
        CatalogProductCustomOptionValueInfoResponseParam _catalogProductCustomOptionValueInfo__return = port.catalogProductCustomOptionValueInfo(_catalogProductCustomOptionValueInfo_parameters);
        System.out.println("catalogProductCustomOptionValueInfo.result=" + _catalogProductCustomOptionValueInfo__return);


        }
        {
        System.out.println("Invoking salesOrderShipmentAddTrack...");
        SalesOrderShipmentAddTrackRequestParam _salesOrderShipmentAddTrack_parameters = null;
        SalesOrderShipmentAddTrackResponseParam _salesOrderShipmentAddTrack__return = port.salesOrderShipmentAddTrack(_salesOrderShipmentAddTrack_parameters);
        System.out.println("salesOrderShipmentAddTrack.result=" + _salesOrderShipmentAddTrack__return);


        }
        {
        System.out.println("Invoking giftMessageSetForQuoteItem...");
        GiftMessageForQuoteItemRequestParam _giftMessageSetForQuoteItem_parameters = null;
        GiftMessageForQuoteItemResponseParam _giftMessageSetForQuoteItem__return = port.giftMessageSetForQuoteItem(_giftMessageSetForQuoteItem_parameters);
        System.out.println("giftMessageSetForQuoteItem.result=" + _giftMessageSetForQuoteItem__return);


        }
        {
        System.out.println("Invoking catalogProductTagAdd...");
        CatalogProductTagAddRequestParam _catalogProductTagAdd_parameters = null;
        CatalogProductTagAddResponseParam _catalogProductTagAdd__return = port.catalogProductTagAdd(_catalogProductTagAdd_parameters);
        System.out.println("catalogProductTagAdd.result=" + _catalogProductTagAdd__return);


        }
        {
        System.out.println("Invoking catalogProductAttributeMediaCurrentStore...");
        CatalogProductAttributeMediaCurrentStoreRequestParam _catalogProductAttributeMediaCurrentStore_parameters = null;
        CatalogProductAttributeMediaCurrentStoreResponseParam _catalogProductAttributeMediaCurrentStore__return = port.catalogProductAttributeMediaCurrentStore(_catalogProductAttributeMediaCurrentStore_parameters);
        System.out.println("catalogProductAttributeMediaCurrentStore.result=" + _catalogProductAttributeMediaCurrentStore__return);


        }
        {
        System.out.println("Invoking catalogProductMultiUpdate...");
        CatalogProductMultiUpdateRequestParam _catalogProductMultiUpdate_parameters = null;
        CatalogProductMultiUpdateResponseParam _catalogProductMultiUpdate__return = port.catalogProductMultiUpdate(_catalogProductMultiUpdate_parameters);
        System.out.println("catalogProductMultiUpdate.result=" + _catalogProductMultiUpdate__return);


        }
        {
        System.out.println("Invoking salesOrderShipmentAddComment...");
        SalesOrderShipmentAddCommentRequestParam _salesOrderShipmentAddComment_parameters = null;
        SalesOrderShipmentAddCommentResponseParam _salesOrderShipmentAddComment__return = port.salesOrderShipmentAddComment(_salesOrderShipmentAddComment_parameters);
        System.out.println("salesOrderShipmentAddComment.result=" + _salesOrderShipmentAddComment__return);


        }
        {
        System.out.println("Invoking giftMessageSetForQuoteProduct...");
        GiftMessageForQuoteProductRequestParam _giftMessageSetForQuoteProduct_parameters = null;
        GiftMessageForQuoteProductResponseParam _giftMessageSetForQuoteProduct__return = port.giftMessageSetForQuoteProduct(_giftMessageSetForQuoteProduct_parameters);
        System.out.println("giftMessageSetForQuoteProduct.result=" + _giftMessageSetForQuoteProduct__return);


        }
        {
        System.out.println("Invoking catalogCategoryLevel...");
        CatalogCategoryLevelRequestParam _catalogCategoryLevel_parameters = null;
        CatalogCategoryLevelResponseParam _catalogCategoryLevel__return = port.catalogCategoryLevel(_catalogCategoryLevel_parameters);
        System.out.println("catalogCategoryLevel.result=" + _catalogCategoryLevel__return);


        }
        {
        System.out.println("Invoking resources...");
        ResourcesRequestParam _resources_parameters = null;
        ResourcesResponseParam _resources__return = port.resources(_resources_parameters);
        System.out.println("resources.result=" + _resources__return);


        }
        {
        System.out.println("Invoking catalogProductAttributeTierPriceUpdate...");
        CatalogProductAttributeTierPriceUpdateRequestParam _catalogProductAttributeTierPriceUpdate_parameters = null;
        CatalogProductAttributeTierPriceUpdateResponseParam _catalogProductAttributeTierPriceUpdate__return = port.catalogProductAttributeTierPriceUpdate(_catalogProductAttributeTierPriceUpdate_parameters);
        System.out.println("catalogProductAttributeTierPriceUpdate.result=" + _catalogProductAttributeTierPriceUpdate__return);


        }
        {
        System.out.println("Invoking shoppingCartShippingList...");
        ShoppingCartShippingListRequestParam _shoppingCartShippingList_parameters = null;
        ShoppingCartShippingListResponseParam _shoppingCartShippingList__return = port.shoppingCartShippingList(_shoppingCartShippingList_parameters);
        System.out.println("shoppingCartShippingList.result=" + _shoppingCartShippingList__return);


        }
        {
        System.out.println("Invoking catalogProductAttributeCreate...");
        CatalogProductAttributeCreateRequestParam _catalogProductAttributeCreate_parameters = null;
        CatalogProductAttributeCreateResponseParam _catalogProductAttributeCreate__return = port.catalogProductAttributeCreate(_catalogProductAttributeCreate_parameters);
        System.out.println("catalogProductAttributeCreate.result=" + _catalogProductAttributeCreate__return);


        }
        {
        System.out.println("Invoking catalogProductAttributeSetAttributeRemove...");
        CatalogProductAttributeSetAttributeRemoveRequestParam _catalogProductAttributeSetAttributeRemove_parameters = null;
        CatalogProductAttributeSetAttributeRemoveResponseParam _catalogProductAttributeSetAttributeRemove__return = port.catalogProductAttributeSetAttributeRemove(_catalogProductAttributeSetAttributeRemove_parameters);
        System.out.println("catalogProductAttributeSetAttributeRemove.result=" + _catalogProductAttributeSetAttributeRemove__return);


        }
        {
        System.out.println("Invoking catalogProductCustomOptionRemove...");
        CatalogProductCustomOptionRemoveRequestParam _catalogProductCustomOptionRemove_parameters = null;
        CatalogProductCustomOptionRemoveResponseParam _catalogProductCustomOptionRemove__return = port.catalogProductCustomOptionRemove(_catalogProductCustomOptionRemove_parameters);
        System.out.println("catalogProductCustomOptionRemove.result=" + _catalogProductCustomOptionRemove__return);


        }
        {
        System.out.println("Invoking shoppingCartCustomerAddresses...");
        ShoppingCartCustomerAddressesRequestParam _shoppingCartCustomerAddresses_parameters = null;
        ShoppingCartCustomerAddressesResponseParam _shoppingCartCustomerAddresses__return = port.shoppingCartCustomerAddresses(_shoppingCartCustomerAddresses_parameters);
        System.out.println("shoppingCartCustomerAddresses.result=" + _shoppingCartCustomerAddresses__return);


        }
        {
        System.out.println("Invoking salesOrderInvoiceCapture...");
        SalesOrderInvoiceCaptureRequestParam _salesOrderInvoiceCapture_parameters = null;
        SalesOrderInvoiceCaptureResponseParam _salesOrderInvoiceCapture__return = port.salesOrderInvoiceCapture(_salesOrderInvoiceCapture_parameters);
        System.out.println("salesOrderInvoiceCapture.result=" + _salesOrderInvoiceCapture__return);


        }
        {
        System.out.println("Invoking salesOrderUnhold...");
        SalesOrderUnholdRequestParam _salesOrderUnhold_parameters = null;
        SalesOrderUnholdResponseParam _salesOrderUnhold__return = port.salesOrderUnhold(_salesOrderUnhold_parameters);
        System.out.println("salesOrderUnhold.result=" + _salesOrderUnhold__return);


        }
        {
        System.out.println("Invoking shoppingCartCouponRemove...");
        ShoppingCartCouponRemoveRequestParam _shoppingCartCouponRemove_parameters = null;
        ShoppingCartCouponRemoveResponseParam _shoppingCartCouponRemove__return = port.shoppingCartCouponRemove(_shoppingCartCouponRemove_parameters);
        System.out.println("shoppingCartCouponRemove.result=" + _shoppingCartCouponRemove__return);


        }
        {
        System.out.println("Invoking catalogProductAttributeMediaList...");
        CatalogProductAttributeMediaListRequestParam _catalogProductAttributeMediaList_parameters = null;
        CatalogProductAttributeMediaListResponseParam _catalogProductAttributeMediaList__return = port.catalogProductAttributeMediaList(_catalogProductAttributeMediaList_parameters);
        System.out.println("catalogProductAttributeMediaList.result=" + _catalogProductAttributeMediaList__return);


        }
        {
        System.out.println("Invoking catalogProductSetSpecialPrice...");
        CatalogProductSetSpecialPriceRequestParam _catalogProductSetSpecialPrice_parameters = null;
        CatalogProductSetSpecialPriceResponseParam _catalogProductSetSpecialPrice__return = port.catalogProductSetSpecialPrice(_catalogProductSetSpecialPrice_parameters);
        System.out.println("catalogProductSetSpecialPrice.result=" + _catalogProductSetSpecialPrice__return);


        }
        {
        System.out.println("Invoking catalogProductAttributeSetAttributeAdd...");
        CatalogProductAttributeSetAttributeAddRequestParam _catalogProductAttributeSetAttributeAdd_parameters = null;
        CatalogProductAttributeSetAttributeAddResponseParam _catalogProductAttributeSetAttributeAdd__return = port.catalogProductAttributeSetAttributeAdd(_catalogProductAttributeSetAttributeAdd_parameters);
        System.out.println("catalogProductAttributeSetAttributeAdd.result=" + _catalogProductAttributeSetAttributeAdd__return);


        }
        {
        System.out.println("Invoking shoppingCartProductList...");
        ShoppingCartProductListRequestParam _shoppingCartProductList_parameters = null;
        ShoppingCartProductListResponseParam _shoppingCartProductList__return = port.shoppingCartProductList(_shoppingCartProductList_parameters);
        System.out.println("shoppingCartProductList.result=" + _shoppingCartProductList__return);


        }
        {
        System.out.println("Invoking catalogProductAttributeAddOption...");
        CatalogProductAttributeAddOptionRequestParam _catalogProductAttributeAddOption_parameters = null;
        CatalogProductAttributeAddOptionResponseParam _catalogProductAttributeAddOption__return = port.catalogProductAttributeAddOption(_catalogProductAttributeAddOption_parameters);
        System.out.println("catalogProductAttributeAddOption.result=" + _catalogProductAttributeAddOption__return);


        }
        {
        System.out.println("Invoking shoppingCartProductRemove...");
        ShoppingCartProductRemoveRequestParam _shoppingCartProductRemove_parameters = null;
        ShoppingCartProductRemoveResponseParam _shoppingCartProductRemove__return = port.shoppingCartProductRemove(_shoppingCartProductRemove_parameters);
        System.out.println("shoppingCartProductRemove.result=" + _shoppingCartProductRemove__return);


        }
        {
        System.out.println("Invoking catalogProductLinkRemove...");
        CatalogProductLinkRemoveRequestParam _catalogProductLinkRemove_parameters = null;
        CatalogProductLinkRemoveResponseParam _catalogProductLinkRemove__return = port.catalogProductLinkRemove(_catalogProductLinkRemove_parameters);
        System.out.println("catalogProductLinkRemove.result=" + _catalogProductLinkRemove__return);


        }
        {
        System.out.println("Invoking shoppingCartLicense...");
        ShoppingCartLicenseRequestParam _shoppingCartLicense_parameters = null;
        ShoppingCartLicenseResponseParam _shoppingCartLicense__return = port.shoppingCartLicense(_shoppingCartLicense_parameters);
        System.out.println("shoppingCartLicense.result=" + _shoppingCartLicense__return);


        }
        {
        System.out.println("Invoking catalogProductAttributeSetList...");
        CatalogProductAttributeSetListRequestParam _catalogProductAttributeSetList_parameters = null;
        CatalogProductAttributeSetListResponseParam _catalogProductAttributeSetList__return = port.catalogProductAttributeSetList(_catalogProductAttributeSetList_parameters);
        System.out.println("catalogProductAttributeSetList.result=" + _catalogProductAttributeSetList__return);


        }
        {
        System.out.println("Invoking catalogProductCustomOptionValueRemove...");
        CatalogProductCustomOptionValueRemoveRequestParam _catalogProductCustomOptionValueRemove_parameters = null;
        CatalogProductCustomOptionValueRemoveResponseParam _catalogProductCustomOptionValueRemove__return = port.catalogProductCustomOptionValueRemove(_catalogProductCustomOptionValueRemove_parameters);
        System.out.println("catalogProductCustomOptionValueRemove.result=" + _catalogProductCustomOptionValueRemove__return);


        }
        {
        System.out.println("Invoking salesOrderInvoiceVoid...");
        SalesOrderInvoiceVoidRequestParam _salesOrderInvoiceVoid_parameters = null;
        SalesOrderInvoiceVoidResponseParam _salesOrderInvoiceVoid__return = port.salesOrderInvoiceVoid(_salesOrderInvoiceVoid_parameters);
        System.out.println("salesOrderInvoiceVoid.result=" + _salesOrderInvoiceVoid__return);


        }
        {
        System.out.println("Invoking catalogCategoryMove...");
        CatalogCategoryMoveRequestParam _catalogCategoryMove_parameters = null;
        CatalogCategoryMoveResponseParam _catalogCategoryMove__return = port.catalogCategoryMove(_catalogCategoryMove_parameters);
        System.out.println("catalogCategoryMove.result=" + _catalogCategoryMove__return);


        }
        {
        System.out.println("Invoking salesOrderAddComment...");
        SalesOrderAddCommentRequestParam _salesOrderAddComment_parameters = null;
        SalesOrderAddCommentResponseParam _salesOrderAddComment__return = port.salesOrderAddComment(_salesOrderAddComment_parameters);
        System.out.println("salesOrderAddComment.result=" + _salesOrderAddComment__return);


        }
        {
        System.out.println("Invoking salesOrderHold...");
        SalesOrderHoldRequestParam _salesOrderHold_parameters = null;
        SalesOrderHoldResponseParam _salesOrderHold__return = port.salesOrderHold(_salesOrderHold_parameters);
        System.out.println("salesOrderHold.result=" + _salesOrderHold__return);


        }
        {
        System.out.println("Invoking shoppingCartPaymentMethod...");
        ShoppingCartPaymentMethodRequestParam _shoppingCartPaymentMethod_parameters = null;
        ShoppingCartPaymentMethodResponseParam _shoppingCartPaymentMethod__return = port.shoppingCartPaymentMethod(_shoppingCartPaymentMethod_parameters);
        System.out.println("shoppingCartPaymentMethod.result=" + _shoppingCartPaymentMethod__return);


        }
        {
        System.out.println("Invoking salesOrderInvoiceList...");
        SalesOrderInvoiceListRequestParam _salesOrderInvoiceList_parameters = null;
        SalesOrderInvoiceListResponseParam _salesOrderInvoiceList__return = port.salesOrderInvoiceList(_salesOrderInvoiceList_parameters);
        System.out.println("salesOrderInvoiceList.result=" + _salesOrderInvoiceList__return);


        }
        {
        System.out.println("Invoking catalogCategoryAssignedProducts...");
        CatalogCategoryAssignedProductsRequestParam _catalogCategoryAssignedProducts_parameters = null;
        CatalogCategoryAssignedProductsResponseParam _catalogCategoryAssignedProducts__return = port.catalogCategoryAssignedProducts(_catalogCategoryAssignedProducts_parameters);
        System.out.println("catalogCategoryAssignedProducts.result=" + _catalogCategoryAssignedProducts__return);


        }
        {
        System.out.println("Invoking shoppingCartCouponAdd...");
        ShoppingCartCouponAddRequestParam _shoppingCartCouponAdd_parameters = null;
        ShoppingCartCouponAddResponseParam _shoppingCartCouponAdd__return = port.shoppingCartCouponAdd(_shoppingCartCouponAdd_parameters);
        System.out.println("shoppingCartCouponAdd.result=" + _shoppingCartCouponAdd__return);


        }
        {
        System.out.println("Invoking catalogProductLinkTypes...");
        CatalogProductLinkTypesRequestParam _catalogProductLinkTypes_parameters = null;
        CatalogProductLinkTypesResponseParam _catalogProductLinkTypes__return = port.catalogProductLinkTypes(_catalogProductLinkTypes_parameters);
        System.out.println("catalogProductLinkTypes.result=" + _catalogProductLinkTypes__return);


        }
        {
        System.out.println("Invoking salesOrderShipmentSendInfo...");
        SalesOrderShipmentSendInfoRequestParam _salesOrderShipmentSendInfo_parameters = null;
        SalesOrderShipmentSendInfoResponseParam _salesOrderShipmentSendInfo__return = port.salesOrderShipmentSendInfo(_salesOrderShipmentSendInfo_parameters);
        System.out.println("salesOrderShipmentSendInfo.result=" + _salesOrderShipmentSendInfo__return);


        }
        {
        System.out.println("Invoking catalogCategoryInfo...");
        CatalogCategoryInfoRequestParam _catalogCategoryInfo_parameters = null;
        CatalogCategoryInfoResponseParam _catalogCategoryInfo__return = port.catalogCategoryInfo(_catalogCategoryInfo_parameters);
        System.out.println("catalogCategoryInfo.result=" + _catalogCategoryInfo__return);


        }
        {
        System.out.println("Invoking catalogProductAttributeTierPriceInfo...");
        CatalogProductAttributeTierPriceInfoRequestParam _catalogProductAttributeTierPriceInfo_parameters = null;
        CatalogProductAttributeTierPriceInfoResponseParam _catalogProductAttributeTierPriceInfo__return = port.catalogProductAttributeTierPriceInfo(_catalogProductAttributeTierPriceInfo_parameters);
        System.out.println("catalogProductAttributeTierPriceInfo.result=" + _catalogProductAttributeTierPriceInfo__return);


        }

        System.exit(0);
    }

}
