
/*
 * Copyright (c) SiteWhere, LLC. All rights reserved. http://www.sitewhere.com
 *
 * The software in this package is published under the terms of the CPAL v1.0
 * license, a copy of which has been included with this distribution in the
 * LICENSE.txt file.
 */

/*
 * 
 */

package com.openiot.assetmodule.magento.ws;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import java.net.MalformedURLException;
import java.net.URL;

/**
 * This class was generated by Apache CXF 2.3.1
 * Fri Oct 18 03:30:17 EDT 2013
 * Generated source version: 2.3.1
 * 
 */


@WebServiceClient(name = "MagentoService", 
                  wsdlLocation = "http://magento1.com/magento/index.php/api/v2_soap?wsdl",
                  targetNamespace = "urn:Magento") 
public class MagentoService extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("urn:Magento", "MagentoService");
    public final static QName MageApiModelServerWsiHandlerPort = new QName("urn:Magento", "Mage_Api_Model_Server_Wsi_HandlerPort");
    static {
        URL url = null;
        try {
            url = new URL("http://magento1.com/magento/index.php/api/v2_soap?wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from http://magento1.com/magento/index.php/api/v2_soap?wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public MagentoService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public MagentoService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MagentoService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     * 
     * @return
     *     returns MageApiModelServerWsiHandlerPortType
     */
    @WebEndpoint(name = "Mage_Api_Model_Server_Wsi_HandlerPort")
    public MageApiModelServerWsiHandlerPortType getMageApiModelServerWsiHandlerPort() {
        return super.getPort(MageApiModelServerWsiHandlerPort, MageApiModelServerWsiHandlerPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MageApiModelServerWsiHandlerPortType
     */
    @WebEndpoint(name = "Mage_Api_Model_Server_Wsi_HandlerPort")
    public MageApiModelServerWsiHandlerPortType getMageApiModelServerWsiHandlerPort(WebServiceFeature... features) {
        return super.getPort(MageApiModelServerWsiHandlerPort, MageApiModelServerWsiHandlerPortType.class, features);
    }

}
