		<%--
  ~ Copyright (c) SiteWhere, LLC. All rights reserved. http://www.sitewhere.com
  ~
  ~ The software in this package is published under the terms of the CPAL v1.0
  ~ license, a copy of which has been included with this distribution in the
  ~ LICENSE.txt file.
  --%>

</div>
		<div style="height: 10px;"></div>
		<div class="sw-footer">
			<span style="position: absolute; right: 10px; color: #999;">
				${version.versionIdentifier}.${version.buildTimestamp} (${version.editionIdentifier})
			</span>
			Powered by OpenIoT, LLC.
		</div>
	</div>
<script src="${pageContext.request.contextPath}/scripts/bootstrap.min.js"></script>
</body>
</html>